export {default as Introduction} from './Introduction'
export {default as About} from './About'
export {default as Resume} from './Resume'
export {default as Services} from './Services'
export {default as Skills} from './Skills'
export {default as Portfolio} from './Portfolio'
export {default as Contact} from './Contact'